# Generated by Django 5.2.15 on 2026-07-24 06:03

from django.db import migrations
from django.db.models import Q


def cleanup_retired_manual_verifications(apps, schema_editor):
    """Clear PII, then delete matching retired-user manual verification rows."""
    db_alias = schema_editor.connection.alias
    ManualVerification = apps.get_model('verify_student', 'ManualVerification')

    retired_user_filter = (
        Q(user__username__startswith='retired__user_') |
        (
            Q(user__email__startswith='retired__user_') &
            Q(user__email__endswith='@retired.invalid')
        )
    )

    retired_records = ManualVerification.objects.using(db_alias).filter(retired_user_filter)

    # Clear PII, then delete matching records.
    retired_records.update(name='')
    retired_records.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("verify_student", "0016_remove_verificationattempt_created_and_more"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_retired_manual_verifications,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
